services:
  selenium-python:
    build: .
    entrypoint:
      - /bin/bash
    image: futureys/selenium-python:development
    user: root
    volumes:
      - .:/workspace
      - /workspace/.selenium-cache
