services:
  selenium-python:
    build: .
    entrypoint:
      - /bin/bash
    image: futureys/selenium-python:development
    ports:
      # For gatsby develop
      - "8000:8000"
    user: root
    volumes:
      - .:/workspace
      - /workspace/.selenium-cache
