on:
  push:
    tags:
      - 'v[0-9][0-9][0-9][0-9][01][0-9][0-3][0-9][0-2][0-9][0-5][0-9][0-5][0-9]'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - id: extract-tag
        run: echo ::set-output name=DOCKER_TAG::$(echo ${GITHUB_REF#refs/tags/v})
      - uses: docker/build-push-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/selenium-python:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/selenium-python:buildcache,mode=max
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/selenium-python:latest,${{ secrets.DOCKER_HUB_USERNAME }}/selenium-python:${{ steps.extract-tag.outputs.DOCKER_TAG }}
