name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/selenium-python:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/selenium-python:buildcache,mode=max
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/selenium-python:test
      - uses: actions/checkout@v4
      - run: docker compose -f compose.test.yml run --rm selenium-python python --help
      - uses: actions/checkout@v4
      # Should print "selenium"
      - run: docker compose -f compose.test.yml run --rm --user root --entrypoint '' selenium-python sudo -u selenium uv run whoami
